### ISSUE TITLE
Improvement: Store stream and action events to trigger on newly created views 

### ISSUE THREAD

**Issue by tomaszdurka** [cargomedia/cm#1874]
Idea is to not miss any event on newly created view. Currently if event connected with the view occurs while it's being loaded it might be missed. Especially important when occuring after server-side rendering of the view.

Idea to solve it is to store triggered actions, stream events and run newly bound callbacks if within applicable timespan (between current time and server render time).

**Comment by tomaszdurka** [comment]
@njam @vogdb wdyt?

**Comment by vogdb** [comment]
Sounds good but where we can store those triggered actions, etc. ?

**Comment by njam** [comment]
We *do* have such a event buffer in socket-redis:
- In `CM_RenderAdapter_Layout` (php) we assign the current time to the frontend as `renderStamp`.
- In `CM_MessageStream_Adapter_SocketRedis` (js) we pass it to SocketRedis:
```js
this._socketRedis.subscribe(channel, cm.options.renderStamp, data, onmessage);
```
- Socket redis will deliver all messages since the `renderStamp` that are buffered. See https://github.com/cargomedia/socket-redis/blob/master/lib/worker.js#L169

Does this solve the issue?

**Comment by tomaszdurka** [comment]
Hmm, yes but this is way more general and for whole application? I am looking for something more internal. We trigger all the events correctly atm. It's just that some events are bound after the trigger they should respond to. 
Easiest way to reproduce it is to `sleep(10)` after the component is rendered on the serverside, then on client-side trigger some events on that chat (like chat message). They will be ignored.

I think this would need to be additional mechanism implemented regardless of socket-redis adapter.
Thought that my issue explanation will be quite informative :panda_face: or I am missing some point here @njam ?

**Comment by njam** [comment]
As discussed with Tomasz, idea would be:
- `CM_View_Abstract` would get a `renderStamp` assigned on the server side
- `CM_View_Abstract.bindStream()` (and `CM_View_Abstract.bindAction()`) would pass this timeStamp to `cm.stream.bind()`
- `cm.stream.bind()` would immediately trigger past events since the timeStamp. 

For this the stream-callback which triggers the events in `cm.stream._subscribe()` would need to store all events. Old entries in this events cache should be expired after 10 seconds (`setTimeout()`?).

**Comment by vogdb** [comment]
> - `CM_View_Abstract` would get a `renderStamp` assigned on the server side

Any hints on that ? Where to implement this?

**Comment by njam** [comment]
@tomaszdurka can you look into this with Aleksei? RenderAdapter? We don't have a generic one for all views.

**Comment by tomaszdurka** [comment]
@vogdb do you want to look into this on your own?

**Comment by vogdb** [comment]
ok, will look

**Comment by njam** [comment]
Tomasz explained the topic to me as follows:
- Every component rendered on the server will have a "renderStamp" associated.
- When such a component is injected on the client we would iterate through past events in `cm.stream` (will need to store events for a certain amount of time).
- The events that happened between the component's "renderStamp" and now will be re-triggered for any bindings that the new component made on the dispatcher (having the same `context`). This only applies to calls to `bind()` that happened during `ready()`/`_ready()` of the component.

It's quite a complicated task and will make the code in `cm.stream` make less readable.
*If* you decide to work on this, I think it would be good to rewrite that code a bit.
Let's do https://github.com/cargomedia/cm/issues/2042 first

**Comment by njam** [comment]
Closing for now
