### ISSUE TITLE
Define sub-module structure

### ISSUE THREAD

**Issue by njam** [cargomedia/cm#1883]
Add some documentation about suggested "sub-module" directory structure to the README.

Define where to put and how to name:
- Models
- Pagings
- Other things

---

Examples:
```
library/Denkmal/library/Denkmal/Push/
├── ClientConfiguration.php
├── Notification
│   ├── Message.php
│   ├── MessageList
│   │   ├── Abstract.php
│   │   ├── Expired.php
│   │   └── Subscription.php
│   ├── Provider
│   │   ├── Abstract.php
│   │   └── GoogleCloudMessaging.php
│   └── Sender.php
├── Subscription.php
└── SubscriptionList
    ├── Abstract.php
    ├── All.php
    └── Expired.php
```
```
library/SK/library/SK/Payments/
├── Bank.php
├── ExchangeRate
│   └── Updater.php
├── Paging
│   └── Bank
│       ├── Abstract.php
│       ├── All.php
│       └── PaymentProvider.php
├── SetupScript.php
└── TrackingInterface.php
```
```
library/SK/library/SK/Achievement/
├── Badge
│   ├── Default.php
│   └── LevelBased.php
├── Calculator
│   └── Level.php
├── Type
│   ├── Abstract.php
│   ├── Blogposts.php
│   ├── Statuses.php
│   └── Videos.php
├── UserAchievement.php
└── UserAchievementPaging.php
```

**Comment by njam** [comment]
@tomaszdurka @dlondero can you discuss and propose a standard?

**Comment by dlondero** [comment]
I'd exclude last example because I think that having the paging not in a dedicated directory will end up quickly in a great mess.

First and second are quite similar. First has the plus of removing one level for pagings creating dedicated directories and I like that. Still I'm a bit worried of the implementation of namespaces in class names as we'll have something like this `Denkmal_Push_Notification_MessageList_Expired` which is bit ugly.

One important thing is to separate well concepts between modules in order to not have some of them too big with too many levels.

**Comment by njam** [comment]
@fvovan maybe you have some input? Should we discuss it on Wednesday?

**Comment by fvovan** [comment]
Would be good, I will think about it today.

**Comment by njam** [comment]
Closing in favor of https://github.com/cargomedia/cm/pull/1954
