### ISSUE TITLE
MessageStream::startSynchronization respawns regularly

### ISSUE THREAD

**Issue by njam** [cargomedia/cm#1920]
Dies every ~minute and is respawned.
The original reason (exception?) seems not to be logged.

cc @zazabe @alexispeter

**Comment by tomaszdurka** [comment]
- Cannot reproduce locally so far.
- Turns out there is no exception and it exits with 0.
- Not connected with the CLI, we've run startSynchronization separately and still quits.
- We tried running `redis->subscribe()` with simple dumping channel/message and it never died.

**Comment by zazabe** [comment]
after a look at [the diff](https://github.com/phpredis/phpredis/compare/2.2.3...phpredis:2.2.7) between `phpredis 2.2.3` and `phpredis 2.2.7`, there's some improvements that can helps maybe:

- phpredis/phpredis/pull/493 : Allow to break out of subscribe loop   
  the guy fixed a memory leak issue

I'm not sure it will solve this issue, i think the problem is somewhere here: 
https://github.com/phpredis/phpredis/blob/2.2.7/redis.c#L5669

maybe the way we define the callback is overcomplicated, with a callback defined as a property of the redis client (`$_subscribeCallback`) which is also a method name of the same class...
https://github.com/cargomedia/cm/blob/master/library/CM/Redis/Client.php#L273

**Comment by zazabe** [comment]
I created this ticket about phpredis:  [Throw an exception when the subscribe method fail at some point](https://github.com/phpredis/phpredis/issues/662)

FYI, not throwing exception seems to be a decision since the creation of this extension:
> Since the beginning of the phpredis project a design decision was made to not throw exceptions except in the case of communication errors.
https://github.com/phpredis/phpredis/issues/502#issuecomment-54200996

I will investigate https://github.com/nrk/predis to replace phpredis, there's less activity on this project but [Redis recommend it also](http://redis.io/clients#php).

**Comment by njam** [comment]
@zazabe fixed by https://github.com/cargomedia/cm/pull/1923?

**Comment by zazabe** [comment]
@njam I don't see any "Respawning dead child..." warning exception in the admin, so I suppose we can close this ticket, isn't it?

**Comment by njam** [comment]
Very good
