### ISSUE TITLE
_appendDirectoryBrowserify: recursive glob?

### ISSUE THREAD

**Issue by njam** [cargomedia/cm#2288]
Do a recursive glob in `CM_Asset_Javascript_Abstract::_appendDirectoryBrowserify`?
We have `CM_Util::rglob()`.

@zazabe @fauvel wdyt?

**Comment by fauvel** [comment]
Makes sense so that we can organize main source files better (though we have no real use case yet, we mostly need to organize libraries, not main source files) – @zazabe wdyt?

**Comment by zazabe** [comment]
It depends if we already have some use cases, but we could wait for https://github.com/cargomedia/cm/pull/2274, there's just few adjustments to do in [cm-bundler](https://github.com/cargomedia/cm-bundler) to support "glob" as `entries`.

Otherwise, it's also quite straightforward to support it right now ;)

**Comment by zazabe** [comment]
as discussed with @njam, we can wait for #2274
