### ISSUE TITLE
Allow to include "description" in migration file name

### ISSUE THREAD

**Issue by njam** [cargomedia/cm#2403]
Goal: allow to include a *description* in the name of a migration script ("34-some-change" instead of "34"), to avoid VCS conflicts.

This was discussed before in https://github.com/cargomedia/cm/issues/588

The new migration script could extend `CM_Provision_Script_Abstract` and use `CM_Provision_Script_OptionBased` for persisting whether a script has ran or not.
-> Or it could use a separate table, which can be used in more powerful ways in the future (keep timestamps etc).

The filename should still include a timestamp for ordering. For example the file could be named `1478003870-some-change.php` and the class `CM_Provision_Migration_1478003870-some-change`.

We should introduce a CLI helper to create a new migration. The *description* could by default be taken from the GIT branch name.

cc @tomaszdurka @dlondero @fauvel

**Comment by zazabe** [comment]
- Let's use a separate table, maybe auto-generated like described [here](https://github.com/cargomedia/cm/issues/588#issuecomment-78231730)
- I would suggest to always generate the migration class, with a reference to the previous migration script.  
  Then, we could add a CI script to test if there's multiple migration classes with a ref to the same migration script.

```
CM_Provision_MigrationScript extends CM_Model_Abstract
  - filename: string
  - classname: string
  - previous: CM_Provision_MigrationScript|null 
  - execStamp: DateTime  
```

wdyt?

**Comment by njam** [comment]
> previous migration ... test if there's multiple migration classes with a ref to the same migration script

My understand was that this is what we want to allow to do. Two developers should be able to commit a migration script to master both succeeding the same previous migration. In most cases that's not a problem, as there were not conflicts in the code.

@tomaszdurka wdyt?

**Comment by njam** [comment]
As discussed:
- Reuse `CM_Provision_Loader` but add a custom persistence layer for migrations (extending `CM_Provision_Script_Abstract`).
- Add new folder `db/migration/` for the new system, so we can introduce it side-by-side.
- CM_App::runUpdateScripts(): Dropping of test database not needed anymore, because `CM_Db_SetupScript` will drop DB in tests.

**Comment by fauvel** [comment]
An old discussion indeed:) Summary:

The idea is to make a trade-off between:
(a) controlling the execution order of the migration scripts merged from different branches, and
(b) avoiding unnecessary merge conflicts when devs create simultaneously independent migration scripts in different branches.

Usually, the execution order of migration scripts created simultaneously in different branches doesn't really matter. That's why we would like to avoid this kind of merge conflicts, as they only slow down development. So basically, we only want to make sure that newly created migration scripts will be executed after the migration scripts of the base branch. We still want some manual control in cases where we need it, though.

My opinion:
- Extending the name of migration scripts by a short description slug solves the problem in an elegant way
- We could automate the naming convention (with a CLI scaffolding function) by using the branch name as a description slug, e.g. `34-issue-1234`
- There is no need to introduce a new folder for migration scripts, since the new convention is backwards-compatible
- We should store the full file name of all executed scripts in the database

**Comment by njam** [comment]
Michel is implementing a new migration system which such characteristics in https://github.com/cargomedia/cm/issues/2477. It will be a completely new system in a new folder though. This way we can delete the old system without problems afterwards.

**Comment by zazabe** [comment]
closable?

**Comment by zazabe** [comment]
maybe i could add some instructions in the `README.md` about `cm/bin migration`

**Comment by njam** [comment]
sgtm, could you add such a note and then send an email to the team?
After that we can wait a few weeks and then remove the old system.

**Comment by njam** [comment]
We should also add an execution of `bin/cm migration run` to the provisioner in Vagrant, and the [pulsar task on production](https://github.com/cargomedia/pulsar-conf-cargomedia/blob/master/recipes/cm/deploy.rb#L78).
We can remove this task to run a single script, we never use it:
https://github.com/cargomedia/pulsar-conf-cargomedia/blob/master/recipes/cm/deploy.rb#L82

**Comment by njam** [comment]
@zazabe closeable?

**Comment by zazabe** [comment]
yes!
