### ISSUE TITLE
PHP 7 compatibility

### ISSUE THREAD

**Issue by njam** [cargomedia/cm#2478]
Problems:
- [ ] Runkit is not available for mocking `time()` (https://github.com/zenovich/runkit/issues/87)
  - Alternative: https://github.com/hnw/php-timecop
  - Alternative: https://github.com/wolfcw/libfaketime
- [ ] PHP SVM doesn't compile on PHP 7 (https://github.com/ianbarber/php-svm/issues/10) 
- [ ] Gearman requires PHP (version >= 5.1.0, version <= 6.0.0, excluded versions: 6.0.0) (https://pecl.php.net/package/gearman)

**Comment by dlondero** [comment]
AFAIU `runkit_function_redefine` is just used to redefine `time` to return `CMTest_TH::time()` value. This is in order to use `time()` in tests and get the mocked value. And this always appeared like a kind of magic as in the beginning I had to remember what `time()` was going to return (the right time or the frozen one?).

I think **I'm probably missing** some other usage to really feel the need for this, but can't we simply replace `time()` usages with `CMTest_TH::time()` which is even more explicit of what we get?

**Comment by dlondero** [comment]
Looking into `php-timecop` to test it.
