### ISSUE TITLE
Make $encoded param of CM_Params mandatory

### ISSUE THREAD

**Issue by njam** [cargomedia/cm#2574]
It's important to think about what the value of this parameter is, so let's make it mandatory.
It can still optional if $params is empty.

**Comment by alexispeter** [comment]
I'd like to suggest another approach. 
We remove the parameter altogether and instead decide parameter by parameter if it's encoded or decoded. 
Scalar types would be considered decoded AND encoded (because the distinction is only really relevant for objects and objects in array-form), arrays would be considered encoded (they could also be considered both if they are regular arrays but let's not go that far) and objects would be considered decoded.
So instantiating a CM_Params object with mixed types would also lead to a mixed internal representation. E.g.
```php
$params = new CM_Params([
    'foo' => new CM_Model_User(3),
    'bar' => 3,
    'baz' => [
        '_class' => 'CM_Model_User',
        '_type' => 13,
        '_id' => ['id' => "3"],
        etc...
    ],
]);
```
the internal array would look like
```php
$params->_params = [
    'foo' => 
        [
            'encoded' => null,
            'decoded' => CM_Model_User(3),
        ],
    'bar' => 
        [
            'encoded' => 3,
            'decoded' => 3,
        ],
    'baz' => 
        [
            'encoded' => 
                [
                    '_class' => 'CM_Model_User',
                    '_type' => 13,
                    '_id' => ['id' => "3"],
                    etc...
                ],
            'decoded' => null,
        ],
    ];
```

wdyt @njam?

**Comment by njam** [comment]
We discussed it. While it would be nice to use such a heuristic it will get ugly with nested arrays.
We will keep it manually specified through the constructor.
